### ISSUE TITLE
Update black setup

### ISSUE THREAD

**Issue by dkdndes** [osbdr/pipeline-python-demo#8]
At the moment black will check the python setup as well, and find issues within the source code of Python 3.8.2

The expected behavior would be that the default python libraries are left alone and, just the source code of the current python package gets checked.

Required is a change to the config, as provided in a closed pull request. I would be nice to move the config to here and close with this the issue/bug.

**Comment by dkdndes** [comment]
@j0nm1 please check all python related pipeline demos, and lets quickly fix them. Thank you, Peter

**Comment by j0nm1** [comment]
@dkdndes the problem is only related to this repository. The django repository already has a working gitignore.
